<<<<<<< HEAD
INSERT INTO movie (m_title, m_synopsis, m_release, m_director, m_country, m_runningtime, m_poster) VALUES ('제목1', '시놉시스1', '개봉일1' , '감독1', '국가1', '1분', '포경1')
INSERT INTO movie (m_title, m_synopsis, m_release, m_director, m_country, m_runningtime, m_poster) VALUES ('제목2', '시놉시스2', '개봉일2' , '감독2', '국가2', '2분', '포경2')
INSERT INTO movie (m_title, m_synopsis, m_release, m_director, m_country, m_runningtime, m_poster) VALUES ('제목3', '시놉시스3', '개봉일3' , '감독3', '국가3', '3분', '포경3')
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 손흥민 헤트트릭', '손흥민', '2023-10-29', '손흥민의 새로운 게시물 내용입니다.', 42)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 황희찬 리그 2호골', '황희찬', '2023-10-30', '황희찬의 새로운 게시물 내용입니다.', 36)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 김민재 좋은 수비', '김민재', '2023-10-31', '김민재의 새로운 게시물 내용입니다.', 29)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 이강인 프리킥 골', '이강인', '2023-11-01', '이강인의 새로운 게시물 내용입니다.', 63)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 음바페의 니어포스트 골', '음바페', '2023-11-06', '음바페의 새로운 게시물 내용입니다.', 48)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 주드벨링엄의 환상적인 슈팅', '주드벨링엄', '2023-11-07', '주드벨링엄의 새로운 게시물 내용입니다.', 53)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 무시알라의 골', '무시알라', '2023-11-08', '무시알라의 새로운 게시물 내용입니다.', 65)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 필 포든', '필 포든', '2023-11-09', '필 포든의 새로운 게시물 내용입니다.', 43)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 비르츠의 드리블과 패스', '비르츠', '2023-11-10', '비르츠의 새로운 게시물 내용입니다.', 37)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 비니시우스의 드리블', '비니시우스', '2023-11-11', '비니시우스의 새로운 게시물 내용입니다.', 58)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 보니페이스의 결승 골', '보니페이스', '2023-11-12', '보니페이스의 새로운 게시물 내용입니다.', 39)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 해리케인의 프리킥', '해리케인', '2023-11-13', '해리케인의 새로운 게시물 내용입니다.', 55)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 그리즈만의 패스와 슈팅', '그리즈만', '2023-11-14', '그리즈만의 새로운 게시물 내용입니다.', 47)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 홀란드의 강력한 슈팅', '홀란드', '2023-11-15', '홀란드의 새로운 게시물 내용입니다.', 59)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 후벵디아스의  수비', '후벵디아스', '2023-11-16', '후벵디아스의 새로운 게시물 내용입니다.', 41)
INSERT INTO board (b_title, b_writer, b_date, b_content, b_hit) VALUES ('제목은 리로이 자네의 빠른 스피드', '리로이 자네', '2023-11-17', '리로이 자네의 새로운 게시물 내용입니다.', 62)

=======
INSERT INTO movie (m_title, m_synopsis, m_release, m_director, m_country, m_runningtime, m_poster) VALUES ('제목1', '시놉시스1', '개봉일1', '감독1', '국가1', '1분', '포경1')
INSERT INTO movie (m_title, m_synopsis, m_release, m_director, m_country, m_runningtime, m_poster) VALUES ('제목2', '시놉시스2', '개봉일2', '감독2', '국가2', '2분', '포경2')
INSERT INTO movie (m_title, m_synopsis, m_release, m_director, m_country, m_runningtime, m_poster) VALUES ('제목3', '시놉시스3', '개봉일3', '감독3', '국가3', '3분', '포경3')

--INSERT INTO review (m_seq, email, r_rating, r_content, r_liked, r_hated) VALUES ('1', 'kic03@naver.com', '9', '굿굿', '10', '0')
--INSERT INTO review (m_seq, email, r_rating, r_content, r_liked, r_hated) VALUES ('1', 'kic03@naver.com', '8', 'ㅋㅋ', '1', '1')
--INSERT INTO review (m_seq, email, r_rating, r_content, r_liked, r_hated) VALUES ('1', 'kic03@naver.com', '7', '와우', '11', '0')
>>>>>>> 6e22bf48e5130bb7d6151274939303ec1c799a71
